### ISSUE TITLE
Upgrade to Kotlin 1.8 causes problems requiring upgrade of KotlinX/Poet or possible migration to KSP?

### ISSUE THREAD

**Issue by daviddenton** [http4k/http4k-connect#212]
This branch contains the upgrade to Kotlin 1.8, which fails the build with the following message:
```
Caused by: java.lang.IllegalStateException: Could not parse metadata! Try bumping kotlinpoet and/or kotlinx-metadata version.
        at com.squareup.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:90)
        at com.squareup.kotlinpoet.metadata.KotlinPoetMetadata.toKmClass(KotlinPoetMetadata.kt:119)
        at se.ansman.kotshi.kapt.MetadataAccessor.getKmClass(MetadataAccessor.kt:31)
        at se.ansman.kotshi.kapt.MetadataAccessor.getKmClass(MetadataAccessor.kt:32)
        at se.ansman.kotshi.kapt.AdaptersProcessingStep.process(AdaptersProcessingStep.kt:61)
        at se.ansman.kotshi.kapt.KotshiProcessor.process(KotshiProcessor.kt:104)
        at se.ansman.kotshi.kapt.KotshiProcessor.process(KotshiProcessor.kt:86)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:197)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
        ... 51 more
```

We have long suspected that Kapt should eventually be replaced with KSP - see (https://github.com/http4k/http4k-connect/issues/211) for the generation of http4k-connect adapters. It is possible that once KotlinPoet and KotlinX metadata are upgraded this will just work - there are changes to the KotlinX metadata APIs which will need to be released first before Poet can be tackled though.

Creating the [branch](https://github.com/http4k/http4k-connect/tree/kotlin_1_8_upgrade) to track the progress of this.

**Comment by daviddenton** [comment]
Fixed in master now 😄
