### ISSUE TITLE
Fake KMS returns RSA Public Key for ECDSA keySpec

### ISSUE THREAD

**Issue by oharaandrew314** [http4k/http4k-connect#264]
Downloading the public key from the fake KMS client always results in an RSA Public Key.  Both of these tests pass against real KMS.

```kotlin
@Test
    fun `get RSA public key`() {
        val keyId = kms.createKey(RSA_2048, SIGN_VERIFY).successValue().KeyMetadata.KeyId

        try {
            val result = kms.getPublicKey(keyId).successValue()
            val spec = X509EncodedKeySpec(result.PublicKey.decodedBytes())
            KeyFactory.getInstance("RSA").generatePublic(spec)
        } finally {
            val deletion = kms.scheduleKeyDeletion(keyId, 7).successValue()
            assertThat(deletion.KeyId.toARN().value, endsWith(keyId.value))
        }
    }
// PASS

    @Test
    fun `get ECDSA public key`() {
        val keyId = kms.createKey(ECC_NIST_P256, SIGN_VERIFY).successValue().KeyMetadata.KeyId
        Security.addProvider(BouncyCastleProvider())

        try {
            val result = kms.getPublicKey(keyId).successValue()
            val spec = X509EncodedKeySpec(result.PublicKey.decodedBytes())

            KeyFactory.getInstance("ECDSA").generatePublic(spec)
        } finally {
            val deletion = kms.scheduleKeyDeletion(keyId, 7).successValue()
            assertThat(deletion.KeyId.toARN().value, endsWith(keyId.value))
        }
    }
// FAIL
```

```encoded key spec not recognized: algorithm identifier 1.2.840.113549.1.1.1 in key not recognised
java.security.spec.InvalidKeySpecException: encoded key spec not recognized: algorithm identifier 1.2.840.113549.1.1.1 in key not recognised
	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyFactorySpi.engineGeneratePublic(Unknown Source)
	at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:351)
	at org.http4k.connect.amazon.kms.KMSContract.get ECDSA public key(KMSContract.kt:192)
```

**Comment by daviddenton** [comment]
Happy to take a PR for adding the other key type. I have to admit that we've never used it with anything other than RSA. :)

**Comment by daviddenton** [comment]
Fixed by https://github.com/http4k/http4k-connect/pull/265
